jenkins:
    image: jenkins
    ports:
      - 8888:8080
      - 50000:50000

dev-tomcat:
    image: tomcat:8.0
    ports:
      - 8181:8080

jboss:
    build: .
    restart: always
    ports:
      - 9990:9990
      - 8080:8080
      - 8787:8787